/**
 * Error Codes for Geino SaaS Backend
 * 
 * Language-agnostic error codes that map to localized messages on the frontend.
 * These codes ensure the backend stays language-independent while allowing
 * frontend to display user-friendly messages in any language.
 * 
 * Convention: ENTITY_ACTION_REASON format (e.g., TASK_CREATE_FORBIDDEN)
 */

/**
 * Permission/Authorization Error Codes
 */
export const PermissionErrorCodes = {
  // System admin
  SYSTEM_ADMIN_REQUIRED: 'SYSTEM_ADMIN_REQUIRED',
  
  // Task permissions
  NO_TASK_ACCESS: 'NO_TASK_ACCESS',
  NO_TASK_CREATE: 'NO_TASK_CREATE',
  NO_TASK_EDIT: 'NO_TASK_EDIT',
  NO_TASK_DELETE: 'NO_TASK_DELETE',
  NO_TASK_STATUS_CHANGE: 'NO_TASK_STATUS_CHANGE',
  
  // Project permissions
  NO_PROJECT_ACCESS: 'NO_PROJECT_ACCESS',
  NO_PROJECT_CREATE: 'NO_PROJECT_CREATE',
  NO_PROJECT_UPDATE: 'NO_PROJECT_UPDATE',
  NO_PROJECT_DELETE: 'NO_PROJECT_DELETE',
  NO_PROJECT_MANAGE: 'NO_PROJECT_MANAGE',
  
  // Organization permissions
  NO_ORGANIZATION_ACCESS: 'NO_ORGANIZATION_ACCESS',
  NO_ORGANIZATION_CREATE: 'NO_ORGANIZATION_CREATE',
  NO_ORGANIZATION_MANAGE: 'NO_ORGANIZATION_MANAGE',
  
  // Member permissions
  NO_MEMBER_MANAGE: 'NO_MEMBER_MANAGE',
  
  // Attachment permissions
  NO_ATTACHMENT_DELETE: 'NO_ATTACHMENT_DELETE',
  NO_ATTACHMENT_ACCESS: 'NO_ATTACHMENT_ACCESS',
} as const;

/**
 * Validation Error Codes
 */
export const ValidationErrorCodes = {
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  PAST_DEADLINE_NOT_ALLOWED: 'PAST_DEADLINE_NOT_ALLOWED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

/**
 * Resource Error Codes
 */
export const ResourceErrorCodes = {
  // Generic
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  
  // Specific resources
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
} as const;

/**
 * Operation Error Codes
 */
export const OperationErrorCodes = {
  // Task operations
  TASK_CREATE_FAILED: 'TASK_CREATE_FAILED',
  TASK_UPDATE_FAILED: 'TASK_UPDATE_FAILED',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',
  
  // Project operations
  PROJECT_CREATE_FAILED: 'PROJECT_CREATE_FAILED',
  PROJECT_UPDATE_FAILED: 'PROJECT_UPDATE_FAILED',
  PROJECT_DELETE_FAILED: 'PROJECT_DELETE_FAILED',
  
  // Organization operations
  ORGANIZATION_CREATE_FAILED: 'ORGANIZATION_CREATE_FAILED',
  ORGANIZATION_UPDATE_FAILED: 'ORGANIZATION_UPDATE_FAILED',
  ORGANIZATION_DELETE_FAILED: 'ORGANIZATION_DELETE_FAILED',
  
  // Member operations
  MEMBER_ADD_FAILED: 'MEMBER_ADD_FAILED',
  MEMBER_REMOVE_FAILED: 'MEMBER_REMOVE_FAILED',
  
  // File operations
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  ATTACHMENT_DELETE_FAILED: 'ATTACHMENT_DELETE_FAILED',
  ATTACHMENT_DOWNLOAD_FAILED: 'ATTACHMENT_DOWNLOAD_FAILED',
  
  // Notification operations
  NOTIFICATION_LOAD_FAILED: 'NOTIFICATION_LOAD_FAILED',
  NOTIFICATION_UPDATE_FAILED: 'NOTIFICATION_UPDATE_FAILED',
  
  // Auth operations
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_UPDATE_FAILED: 'PASSWORD_UPDATE_FAILED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  
  // User operations
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED: 'USER_DELETE_FAILED',
  USER_SEARCH_FAILED: 'USER_SEARCH_FAILED',
} as const;

/**
 * All error codes combined for easy access
 */
export const ErrorCodes = {
  ...PermissionErrorCodes,
  ...ValidationErrorCodes,
  ...ResourceErrorCodes,
  ...OperationErrorCodes,
} as const;

/**
 * Type for all error codes
 */
export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
